export default {
  OUTPASS_APPROVED: "OUTPASS_APPROVED",
  OUTPASS_REJECTED: "OUTPASS_REJECTED",
  OUTPASS_CREATED: "OUTPASS_CREATED",

  LIBRARY_REMINDER: "LIBRARY_REMINDER",

  EMERGENCY_ALERT: "EMERGENCY_ALERT",
}
